name: 'EventCatalog Governance Action'
description: 'A GitHub Action to enforce EventCatalog governance.'
author: 'EventCatalog'

inputs:
  github_token:
    description: 'GitHub token to interact with the GitHub API'
    required: true
  catalog_directory:
    description: 'The directory where the EventCatalog files are located. If specified, the action will only consider files within this directory.'
    required: false
  OPENAI_API_KEY:
    description: 'OpenAI API key to use for AI processing'
    required: false
  model:
    description: 'The model to use for AI processing. Default is o4-mini.'
    required: false
    default: 'o4-mini'
  provider:
    description: 'The AI Provider to use for AI processing. Default is openai.'
    required: false
    default: 'openai'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'archive' # Choose an icon from https://feathericons.com/
  color: 'blue'   # Choose a color 